# This is a basic workflow to help you get started with Actions

name: Build-snap

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: samuelmeuli/action-snapcraft@v2.1.1
        with:
          # The channel to install Snapcraft from
          channel: stable
          # Skip installation (login only)
          skip_install: no
          # Whether to install and configure lxd (ubuntu18.04 or lower only)
          use_lxd: no
      - name: Run snapcraft
        run: | 
          snapcraft --destructive-mode
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap
          path: "*.snap"
